---
title: 'RMarkdown:  In Class Assignment'
author: "Luis Garcia"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
  ## Everything above this is R code that we need to make the file run! We'll discuss it next class.
```


Reminder: We learned how to do these things in class today, but there is a "Markdown Help" page available in RStudio (and lots of help if you google). 


# In-class Activity, Markdown

**Do not skip reading this line** Create a new section at the end of this file with the title "Your work here", and beneath it, do the following 3 things. To turn this in, make sure you've committed and pushed, and turn in the link to this repository to the assignment on Blackboard. 


1. Make a subsection called Wise words. Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called My semester. Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

I recomend 

- A _subsubheading_ with the name of the artist or author;    
- An example of their writing or lyrics (formatted in a *block of text*);   
- A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. The knitting will produce an html file, which you will also need to stage/commit/push once it exists! 

**Once you're done, remember to commit the changes and push the repo back to your assignment on GitHub!**

# My work here

1. [WiseWords](https://www.quora.com/Who-originally-suggested-that-if-youre-not-paying-for-the-product-you-are-the-product#:~:text=Michael%20Treanor,by%20publisher%20Tim%20O'Reilly.)

> If something is free, you are the product. - Unkown

2. 
### My Semester
|**Course**|*Course Num.*|Professor|
|:---------|:------------|:--------|
|**Data Science**|*2401*|Dr.Shoemaker|
|**Computer Science**|*1411*|Dr.Kamto|
|**Engineering Design**|*2304*|Mr.Mihn Pham|
|**Operations Research**|*4311*|Dr. Redl|
|**Statistical Inference**|*3333*|Dr.Cahoy|

3. 

### I recommend

### Mark Manson

> You and everyone you know are going to be dead soon. And in the short amount of time between here and there, you have a limited amount of fucks to give. Very few, in fact. And if you go around giving a fuck about everything and everyone without conscious thought or choice—well, then you’re going to get fucked.


- Books: 
  + The Subtle Art of Not Giving a F*ck (2016)
  + Everything is F*cked (2019)
  + Love is Not Enough (2020)